@domain = http://localhost:300/api

###
# 게시물 등록
POST {{domain}}/post
Content-Type: application/JSON

{
    "title" : 3,
    "content":2000,
    "password":"배달중"
    }

###
# 사장 : 주문 관리 update / status String : 배달중, 배달완료, 준비중(?)
PATCH  {{domain}}/post/13
Content-Type: application/JSON

{
    "status":"배달 완료"
}

###
# 사장 : 주문 취소 delete (개인적 사유로 사장의 일방적 취소)
DELETE {{domain}}/post/13

### 
# 사장 : 주문 전체 조회
GET {{domain}}/post/store/1


### 
# 고객 : 주문 전체 조회
GET {{domain}}/post/user

###
# 공통? 사장? : 주문 상세 조회
GET {{domain}}/post/13